In [1]:
import pandas as pd
import sklearn

In [2]:
data=pd.read_excel('Movie.xlsx')

In [3]:
data.shape

(3983, 9)

In [4]:
data.size

35847

In [5]:
data.ndim

2

In [6]:
type(data)

pandas.core.frame.DataFrame

In [7]:
data.dtypes

Column1      int64
Title       object
Actors 1    object
Actors 2    object
Actors 3    object
Director    object
Genre       object
Music       object
Producer    object
dtype: object

In [8]:
data.head()

,Column1,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer
0,1,Agneepath,Rishi Kapoor,Sanjay Dutt,Hrithik Roshan,Karan Malhotra,Action,Ajay - Atul,"Karan Johar,Hiroo Johar"
1,2,Bittoo Boss,Pulkit Samrat,Amita Pathak,Rajesh Bakshi,Supavitra Babul,Love Story,Raghav Sachar,"Abhishek Pathak,Kumar Mangat"
2,3,Housefull 2,Akshay Kumar,John Abraham,Rishi Kapoor,Sajid Khan,Comedy,Sajid - Wajid,Sajid Nadiadwala
3,4,Singham,Ajay Devgn,Kajal Aggarwal,Prakash Raj,Rohit Shetty,Action,Ajay - Atul,NaN
4,5,Golmaal 3,Mithun Chakraborty,Ajay Devgn,Kareena Kapoor,Rohit Shetty,Comedy,Pritam,Dillion Mehta

In [9]:
data. tail(10)

,Column1,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer
3973,3982,Yeh Raat Phir Na Aayegi,Jeetendra,NaN,NaN,Nusrat Sayed,Mystery,Rajesh Roshan,"Shabbir Hussain,Zakir Hussain"
3974,3983,Geet,Avinash Wadhavan,Divya Bharti,Laxmikant Berde,Partho Ghosh,Love Story,Bappi Lahiri,Nilima Paul
3975,3984,Zero,Shahrukh Khan,Anushka Sharma,Katrina Kaif,Anand L. Rai,Love Story,Ajay - Atul,Gauri Khan
3976,3985,Once Again,Shefali Shah,Neeraj Kabi,Bidita Bag,Kanwal Sethi,NaN,Talvin Singh,"Ajay G. Rai,Sanjay Gulati"
3977,3986,Jeet Lo Marathon,Aryan Neeraj Anand,Ankita Bahuguna,Preena Jhamb,Aryan Neeraj Anand,NaN,"Dhawal Pandya,Harindu - Veer",Aryan Neeraj Anand
3978,3987,P.K. Lele - A Salesman,Manav Sohal,Brijendra Kala,Shravani Goswami,Manav Sohal,Comedy,Nayab,"Manav Sohal,Shailesh Gosrani"
3979,3988,Dhappa,Shresth Kumar,Varsha Manikchand,Ayub Khan,Siddharth Nagar,NaN,Vivek Bakshi,Siddharth Nagar
3980,3989,Bhaagte Raho,Abhay Kabir Raichand,Riya Deepsi,Rajpal Yadav,Praful Tiwari,NaN,Hyperbol,Sunil Tiwari
3981,3990,Mumbhaii Gangster,Sanjay Kapoor,Mahima Chaudhary,NaN,Rajiv Ranjan Das,Drama,Liyaqat Ajmeri,Sanjay Shah
3982,3991,Simmba,Ranveer Singh,Sara Ali Khan,Ashutosh Rana,Rohit Shetty,NaN,"DJ Chetas,Lijo George,Tanishk","Rohit Shetty,Karan Johar,Hiroo Johar,Apoorva M..."

In [10]:
data.head()

,Column1,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer
0,1,Agneepath,Rishi Kapoor,Sanjay Dutt,Hrithik Roshan,Karan Malhotra,Action,Ajay - Atul,"Karan Johar,Hiroo Johar"
1,2,Bittoo Boss,Pulkit Samrat,Amita Pathak,Rajesh Bakshi,Supavitra Babul,Love Story,Raghav Sachar,"Abhishek Pathak,Kumar Mangat"
2,3,Housefull 2,Akshay Kumar,John Abraham,Rishi Kapoor,Sajid Khan,Comedy,Sajid - Wajid,Sajid Nadiadwala
3,4,Singham,Ajay Devgn,Kajal Aggarwal,Prakash Raj,Rohit Shetty,Action,Ajay - Atul,NaN
4,5,Golmaal 3,Mithun Chakraborty,Ajay Devgn,Kareena Kapoor,Rohit Shetty,Comedy,Pritam,Dillion Mehta

In [11]:
data.drop('Column1',axis=1,inplace=True)

In [12]:
data.head()

,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer
0,Agneepath,Rishi Kapoor,Sanjay Dutt,Hrithik Roshan,Karan Malhotra,Action,Ajay - Atul,"Karan Johar,Hiroo Johar"
1,Bittoo Boss,Pulkit Samrat,Amita Pathak,Rajesh Bakshi,Supavitra Babul,Love Story,Raghav Sachar,"Abhishek Pathak,Kumar Mangat"
2,Housefull 2,Akshay Kumar,John Abraham,Rishi Kapoor,Sajid Khan,Comedy,Sajid - Wajid,Sajid Nadiadwala
3,Singham,Ajay Devgn,Kajal Aggarwal,Prakash Raj,Rohit Shetty,Action,Ajay - Atul,NaN
4,Golmaal 3,Mithun Chakraborty,Ajay Devgn,Kareena Kapoor,Rohit Shetty,Comedy,Pritam,Dillion Mehta

In [13]:
data['Title']

0                    Agneepath
1                  Bittoo Boss
2                  Housefull 2
3                      Singham
4                    Golmaal 3
                 ...
3978    P.K. Lele - A Salesman
3979                    Dhappa
3980              Bhaagte Raho
3981         Mumbhaii Gangster
3982                    Simmba
Name: Title, Length: 3983, dtype: object

In [14]:
data.head()['Title']

0      Agneepath
1    Bittoo Boss
2    Housefull 2
3        Singham
4      Golmaal 3
Name: Title, dtype: object

In [15]:
data.describe()

,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer
count,3983,3951,3235,3143,3931,3944,3803,3621
unique,3953,1552,1510,1506,2023,14,1690,2565
top,Game,Mithun Chakraborty,Suneil Shetty,_x000D__x000D_\n,Kanti Shah,Drama,Anu Malik,Mukesh Bhatt
freq,3,110,32,46,43,1529,147,40

In [16]:
data.tail()['Genre']

3978    Comedy
3979       NaN
3980       NaN
3981     Drama
3982       NaN
Name: Genre, dtype: object

In [17]:
data['Title'].sum

<bound method Series.sum of 0                    Agneepath
1                  Bittoo Boss
2                  Housefull 2
3                      Singham
4                    Golmaal 3
                 ...
3978    P.K. Lele - A Salesman
3979                    Dhappa
3980              Bhaagte Raho
3981         Mumbhaii Gangster
3982                    Simmba
Name: Title, Length: 3983, dtype: object>

In [18]:
data['Genre'].value_counts()

Genre
Drama               1529
Action               522
Comedy               466
Love Story           381
Thriller             318
Horror               178
Adult                162
Rom - Com            133
Mystery               97
Masala                53
Devotional            38
Animation             36
Sci Fi / Fantasy      22
Documentary            9
Name: count, dtype: int64

In [19]:
data.tail()[['Title','Genre']]

                       Title   Genre
3978  P.K. Lele - A Salesman  Comedy
3979                  Dhappa     NaN
3980            Bhaagte Raho     NaN
3981       Mumbhaii Gangster   Drama
3982                  Simmba     NaN

In [20]:
data[data['Genre']=='Comedy']

,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer
2,Housefull 2,Akshay Kumar,John Abraham,Rishi Kapoor,Sajid Khan,Comedy,Sajid - Wajid,Sajid Nadiadwala
4,Golmaal 3,Mithun Chakraborty,Ajay Devgn,Kareena Kapoor,Rohit Shetty,Comedy,Pritam,Dillion Mehta
8,Vicky Donor,Ayushman Khurana,Yami Gautam,Annu Kapoor,Shoojit Sircar,Comedy,"Rochak Kohli,Abhishek - Akshay,Ayushman Khurana","John Abraham,Sunil Lulla,Ronnie Lahiri"
12,Jodi Breakers,R. Madhavan,Bipasha Basu,Omi Vadiya,Ashwini Chaudhary,Comedy,Salim - Sulaiman,Rajesh Rajilal
20,Chaar Din Ki Chandni,Tusshar Kapoor,Kulraj Randhawa,Anupam Kher,Samir Karnik,Comedy,"Sandesh Shandilya,Shiv - Hari,Abhishek Ray,RDB",Samir Karnik
...,...,...,...,...,...,...,...,...
3938,Umar 55 Ki Dil Bachpan Ka,Akshay Anand,Ruchika Pandey,Kader Khan,Ajay Mehra,Comedy,Dilip Sen - Sameer Sen,"Ajay Mehra,K. Akshay"
3939,Badhaai Ho,Ayushman Khurana,Sanya Malhotra,Gajraj Rao,Amit Ravindernath Sharma,Comedy,"Tanishk,Kaushik - Akash,Inder Bawra,Sunny Bawr...","Vineet Jain,Hemant Bhandari,Aleya Sen,Amit Rav..."
3955,Kutte Ki Dum,Tanya Dang,Lalit Singh Rao,Jass Bopariya,Sunil Patel,Comedy,Sunil Patel,Sonika Patel
3956,Summer Camp,Hemant Pandey,Rajesh Puri,Prithvi Zutshi,Kunal V. Singh,Comedy,"R.P. Sony,Gaurav Kaberi,Jeetu Matrix",NaN
3978,P.K. Lele - A Salesman,Manav Sohal,Brijendra Kala,Shravani Goswami,Manav Sohal,Comedy,Nayab,"Manav Sohal,Shailesh Gosrani"

In [21]:
type(data['Genre'])

pandas.core.series.Series

In [22]:
data[data['Genre']=='Adult']

,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer
99,Love Sex Aur Dhokha,Rajkummar Rao,Nushrat Bharucha,Anshuman Jha,Dibakar Banerjee,Adult,Sneha Khanwalkar,"Ekta Kapoor,Priya Sreedharan"
524,Boom,Amitabh Bachchan,Gulshan Grover,Javed Jaffrey,Kaizad Gustad,Adult,"Sandeep Chowta,Talvin Singh",Ayesha Shroff
1116,Chaahat Ek Ehsaas,Manoranjan Jha,Nisha Parulkar,NaN,S. Latif,Adult,Dheeraj Sen,R. Shankar
1200,Secrets Of Sex,Ritesh Raghuvanshi,NaN,NaN,Kumaar Aadarsh,Adult,NaN,"Kumaar Aadarsh,Jaya A.P"
1272,The Dirty Relation,Manoj Pandey,Aakansha Pundir,Shahzad,Kesar Matharu,Adult,"Imran Wasim,Nishad Vaidya,D.J. Sheizwood","Surjit Kumar,Kanwaljeet Matharu"
...,...,...,...,...,...,...,...,...
3430,M.A. Pass,Raj,NaN,NaN,Suresh Kumar Jnr,Adult,NaN,J. Neelam
3467,A Perfect Guest PG,Ankit Raghav,Zoya Rathore,Sparsh Sharma,Rafat Abbas Ali,Adult,Pawan Muradpuri,Praveen Chandel
3513,Lakme,Rayya Labib,S.A. Rashid,Sunil K. Yadav,Sanjay Khandelwal,Adult,Jeetu Bhowmick,Sunil K. Yadav
3664,Ye Kaisa Pesha,Arpita Mali,NaN,NaN,Alok Shrivastava,Adult,Abhijeet Kumar,Suresh Kumar Malakar
3689,Rati Kaamdev,Ankita Chaman,_x000D__x000D_\n,NaN,Suresh Jain,Adult,NaN,Suresh Jain

In [23]:
data[data['Genre']=='Mystery'][['Title','Actors 1','Director']]

                        Title               Actors 1            Director
208           Woodstock Villa          Sikander Kher        Hansal Mehta
251   Manorama Six Feet Under             Abhay Deol       Navdeep Singh
264             36 China Town         Akshaye Khanna      Abbas - Mustan
312                     Jimmy  Mahakshay Chakraborty        Raj N. Sippy
555           Dhund - The Fog          Amar Upadhyay        Shyam Ramsay
...                       ...                    ...                 ...
3815                    Kohra           Armaan Kohli        Partho Ghosh
3820           Aaja Meri Jaan          Krishan Kumar         Ketan Anand
3838              Pehla Nasha          Deepak Tijori  Ashutosh Gowariker
3840                 Bhuchaal            Daboo Malik      Rakesh Kashyap
3973  Yeh Raat Phir Na Aayegi              Jeetendra        Nusrat Sayed

[97 rows x 3 columns]

In [24]:
data['Director'].value_counts()

Director
Kanti Shah       43
Suresh Jain      39
David Dhawan     35
T.L.V. Prasad    31
Vikram Bhatt     31
                 ..
Sanjay Verma      1
Tariq Khan        1
Anil Dhoble       1
Madan Joshi       1
S.P. Rajaram      1
Name: count, Length: 2023, dtype: int64

In [25]:
data['Actors 1'].value_counts()

Actors 1
Mithun Chakraborty    110
Akshay Kumar           80
Ajay Devgn             66
Govinda                61
Sanjay Dutt            60
                     ...
Siddhant Salaria        1
Ayush Sharma            1
Kapil Karzan            1
Anil Bakshi             1
Upasna Khosla           1
Name: count, Length: 1552, dtype: int64

In [26]:
data['Actors 2'].value_counts()

Actors 2
Suneil Shetty      32
Raveena Tandon     32
Karisma Kapoor     29
Juhi Chawla        27
Manisha Koirala    27
                   ..
Channa Ruparel      1
Varun Sharma        1
Gulshan Devaiya     1
Riya Deepsi         1
Sanya Malhotra      1
Name: count, Length: 1510, dtype: int64

In [27]:
data.columns

Index(['Title', 'Actors 1', 'Actors 2', 'Actors 3', 'Director', 'Genre',
       'Music', 'Producer'],
      dtype='object')

In [28]:
data['Genre'].value_counts()

Genre
Drama               1529
Action               522
Comedy               466
Love Story           381
Thriller             318
Horror               178
Adult                162
Rom - Com            133
Mystery               97
Masala                53
Devotional            38
Animation             36
Sci Fi / Fantasy      22
Documentary            9
Name: count, dtype: int64

In [29]:
data[data['Actors 1']=='Ajay Devgn']

,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer
3,Singham,Ajay Devgn,Kajal Aggarwal,Prakash Raj,Rohit Shetty,Action,Ajay - Atul,NaN
43,Dil Toh Baccha Hai Ji,Ajay Devgn,Emraan Hashmi,Omi Vadiya,Madhur Bhandarkar,Comedy,Pritam,"Kumar Mangat,Madhur Bhandarkar"
82,Once Upon A Time In Mumbaai,Ajay Devgn,Emraan Hashmi,Kangana Ranaut,Milan Luthria,Drama,Pritam,"Ekta Kapoor,Shobha Kapoor"
91,Atithi Tum Kab Jaoge?,Ajay Devgn,Konkona Sen Sharma,Paresh Rawal,Ashwini Dhir,Comedy,Pritam,Amita Pathak
104,Aakrosh,Ajay Devgn,Akshaye Khanna,Bipasha Basu,Priyadarshan,Thriller,Pritam,Kumar Mangat
...,...,...,...,...,...,...,...,...
3833,Dil Hai Betaab,Ajay Devgn,Pratibha Sinha,Vivek Mushran,K.C. Bokadia,Drama,Laxmikant - Pyarelal,Avinash Chander
3869,Shaktimaan,Ajay Devgn,Karisma Kapoor,Mukesh Khanna,K.C. Bokadia,Action,Channi Singh,Suresh Bokadia
3875,Sangram,Ajay Devgn,Ayesha Jhulka,Karisma Kapoor,Lawrence D'Souza,Love Story,Nadeem - Shravan,Lawrence D'Souza
3896,Platform,Ajay Devgn,Prithvi,Tisca Chopra,Deepak Pawar,Action,Anand - Milind,Mukesh Duggal
3912,Divyashakti,Ajay Devgn,Raveena Tandon,Amrish Puri,Sameer Malkan,Action,Nadeem - Shravan,Dinesh Patel

In [30]:
data[data['Director']=='Rohit Shetty'][['Director','Actors 1', 'Title']]

          Director            Actors 1                      Title
3     Rohit Shetty          Ajay Devgn                    Singham
4     Rohit Shetty  Mithun Chakraborty                  Golmaal 3
141   Rohit Shetty         Sanjay Dutt  All The Best - Fun Begins
180   Rohit Shetty          Ajay Devgn                     Sunday
259   Rohit Shetty          Ajay Devgn               Bol Bachchan
296   Rohit Shetty          Ajay Devgn    Golmaal - Fun Unlimited
308   Rohit Shetty          Ajay Devgn            Golmaal Returns
516   Rohit Shetty          Ajay Devgn                     Zameen
1294  Rohit Shetty       Shahrukh Khan            Chennai Express
2279  Rohit Shetty          Ajay Devgn            Singham Returns
3177  Rohit Shetty       Shahrukh Khan                    Dilwale
3606  Rohit Shetty          Ajay Devgn              Golmaal Again
3982  Rohit Shetty       Ranveer Singh                     Simmba

In [31]:
data[(data['Actors 1'] == 'Shahrukh Khan') & (data['Genre'] == 'Thriller')][['Director', 'Title', 'Actors 3']]

            Director     Title           Actors 3
3244  Maneesh Sharma       Fan  Waluscha De Sousa
3806  Abbas - Mustan  Baazigar          Siddharth

In [32]:
data[data['Actors 1']=='Shahrukh Khan']['Genre'].value_counts()

Genre
Drama         10
Love Story     9
Action         8
Masala         6
Rom - Com      3
Thriller       2
Name: count, dtype: int64

In [33]:
data[(data['Actors 1']=='Shahrukh Khan') & (data['Genre']=='Masala')][['Title','Producer']]

                Title                                           Producer
263      Om Shanti Om                                         Gauri Khan
447      Main Hoon Na                                         Gauri Khan
1294  Chennai Express  Ronnie Screwvala,Gauri Khan,Karim Morani,Siddh...
2334   Happy New Year                                         Gauri Khan
2561        Duplicate                                         Yash Johar
3177          Dilwale                                         Gauri Khan

In [34]:
data[data['Actors 1']=='Shahrukh Khan']['Producer'].value_counts()

Producer
Gauri Khan                                                      8
Yash Chopra,Aditya Chopra                                       3
Farhan Akhtar,Ritesh Sidhwani                                   2
Aditya Chopra                                                   2
Yash Johar                                                      2
Ritesh G. Nayyar                                                1
Ashutosh Gowariker                                              1
Hiroo Johar,Gauri Khan                                          1
Bharat Shah                                                     1
Aziz Mirza,Shahrukh Khan,Juhi Chawla                            1
Nazir Ahmed,Radhika Sangoi                                      1
Radhika Sangoi                                                  1
Shahrukh Khan,Aziz Mirza,Juhi Chawla                            1
Ronnie Screwvala,Gauri Khan,Karim Morani,Siddharth Roy Kapur    1
Ram Gopal Verma,Mani Ratnam,Shekhar Kapur                       1
Subhash Ghai                                                    1
Rakesh Roshan                                                   1
Praveen Nischol                                                 1
Pravesh Mehra                                                   1
Prem H. Lalwani                                                 1
Yash Chopra                                                     1
Vikram Mehrohtra                                                1
Gauri Khan,Farhan Akhtar,Ritesh Sidhwani                        1
Ganesh Jain                                                     1
Name: count, dtype: int64

In [35]:
data[(data['Actors 1']=='Shahrukh Khan') & (data['Producer']=='Gauri Khan') & (data['Genre']=='Masala')]['Title']

263       Om Shanti Om
447       Main Hoon Na
2334    Happy New Year
3177           Dilwale
Name: Title, dtype: object

In [36]:
data[data['Producer'] == 'Gauri Khan,Farhan Akhtar,Ritesh Sidhwani'][['Title', 'Genre']]

      Title   Genre
3438  Raees  Action

In [37]:
data['Actors 1'].value_counts()

Actors 1
Mithun Chakraborty    110
Akshay Kumar           80
Ajay Devgn             66
Govinda                61
Sanjay Dutt            60
                     ...
Siddhant Salaria        1
Ayush Sharma            1
Kapil Karzan            1
Anil Bakshi             1
Upasna Khosla           1
Name: count, Length: 1552, dtype: int64

In [38]:
data[data['Actors 1']=='Ajay Devgn']['Director'].value_counts()

Director
Rohit Shetty          8
Harry Baweja          5
Milan Luthria         4
Prakash Jha           3
K.C. Bokadia          2
Rajkumar Santoshi     2
Ram Gopal Verma       2
Deepak Bahry          2
Ajay Devgn            2
Anees Bazmee          2
Raj Kanwar            2
Kuku Kohli            2
Vishal Bhardwaj       1
Anubhav Sinha         1
Ashwini Dhir          1
Madhur Bhandarkar     1
Priyadarshan          1
Kireet Khurana        1
Mani Ratnam           1
Indra Kumar           1
Anil Devgan           1
Deepak Shivdasani     1
Mahesh Manjrekar      1
Kamal                 1
Soham Shah            1
Mani Shankar          1
Govind Nihalani       1
John M. Matthan       1
Sajid Khan            1
Ashok Gaikwad         1
Mahesh Bhatt          1
Prabhu Deva           1
Nishikant Kamat       1
P. Vasu               1
Guddu Dhanoa          1
Faroogh Siddiqui      1
K. Vishwanath         1
Sushama Shiromanee    1
Raj Kumar Gupta       1
Lawrence D'Souza      1
Deepak Pawar          1
Sameer Malkan         1
Name: count, dtype: int64

In [39]:
data[(data['Actors 1'] == 'Ajay Devgn') & (data['Director'] == 'Rohit Shetty')]['Genre'].value_counts()

Genre
Comedy    5
Action    3
Name: count, dtype: int64

In [40]:
data.head()

,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer
0,Agneepath,Rishi Kapoor,Sanjay Dutt,Hrithik Roshan,Karan Malhotra,Action,Ajay - Atul,"Karan Johar,Hiroo Johar"
1,Bittoo Boss,Pulkit Samrat,Amita Pathak,Rajesh Bakshi,Supavitra Babul,Love Story,Raghav Sachar,"Abhishek Pathak,Kumar Mangat"
2,Housefull 2,Akshay Kumar,John Abraham,Rishi Kapoor,Sajid Khan,Comedy,Sajid - Wajid,Sajid Nadiadwala
3,Singham,Ajay Devgn,Kajal Aggarwal,Prakash Raj,Rohit Shetty,Action,Ajay - Atul,NaN
4,Golmaal 3,Mithun Chakraborty,Ajay Devgn,Kareena Kapoor,Rohit Shetty,Comedy,Pritam,Dillion Mehta

In [41]:
data[data['Producer']=='Karan Johar']

,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer
317,Dostana,Abhishek Bachchan,John Abraham,Priyanka Chopra,Tarun Mansukhani,Rom - Com,Vishal - Shekhar,Karan Johar

In [42]:
data['Music'].value_counts()

Music
Anu Malik                                           147
Anand - Milind                                      127
Pritam                                               84
Bappi Lahiri                                         78
Nadeem - Shravan                                     76
                                                   ...
Siddharth Parashar                                    1
Arghya,Arko Pravo Mukherjee,Ramji Gulati              1
Santokh Singh,Rahul Bhatt,Nishant Kamal Vyas          1
M.M. Kreem,Anu Malik                                  1
Avinash Vyas,DJ Chetas,Lijo George,Tanishk,Jam 8      1
Name: count, Length: 1690, dtype: int64

In [43]:
data.shape

(3983, 8)

In [44]:
data.loc[3,'Producer']

nan

In [45]:
data.head()['Producer']

0         Karan Johar,Hiroo Johar
1    Abhishek Pathak,Kumar Mangat
2                Sajid Nadiadwala
3                             NaN
4                   Dillion Mehta
Name: Producer, dtype: object

In [46]:
data.head()

,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer
0,Agneepath,Rishi Kapoor,Sanjay Dutt,Hrithik Roshan,Karan Malhotra,Action,Ajay - Atul,"Karan Johar,Hiroo Johar"
1,Bittoo Boss,Pulkit Samrat,Amita Pathak,Rajesh Bakshi,Supavitra Babul,Love Story,Raghav Sachar,"Abhishek Pathak,Kumar Mangat"
2,Housefull 2,Akshay Kumar,John Abraham,Rishi Kapoor,Sajid Khan,Comedy,Sajid - Wajid,Sajid Nadiadwala
3,Singham,Ajay Devgn,Kajal Aggarwal,Prakash Raj,Rohit Shetty,Action,Ajay - Atul,NaN
4,Golmaal 3,Mithun Chakraborty,Ajay Devgn,Kareena Kapoor,Rohit Shetty,Comedy,Pritam,Dillion Mehta

In [47]:
data.shape

(3983, 8)

In [48]:
data.tail()

,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer
3978,P.K. Lele - A Salesman,Manav Sohal,Brijendra Kala,Shravani Goswami,Manav Sohal,Comedy,Nayab,"Manav Sohal,Shailesh Gosrani"
3979,Dhappa,Shresth Kumar,Varsha Manikchand,Ayub Khan,Siddharth Nagar,NaN,Vivek Bakshi,Siddharth Nagar
3980,Bhaagte Raho,Abhay Kabir Raichand,Riya Deepsi,Rajpal Yadav,Praful Tiwari,NaN,Hyperbol,Sunil Tiwari
3981,Mumbhaii Gangster,Sanjay Kapoor,Mahima Chaudhary,NaN,Rajiv Ranjan Das,Drama,Liyaqat Ajmeri,Sanjay Shah
3982,Simmba,Ranveer Singh,Sara Ali Khan,Ashutosh Rana,Rohit Shetty,NaN,"DJ Chetas,Lijo George,Tanishk","Rohit Shetty,Karan Johar,Hiroo Johar,Apoorva M..."

In [49]:
data.size

31864

In [50]:
data.shape

(3983, 8)

In [51]:
data.isnull()

      Title  Actors 1  Actors 2  Actors 3  Director  Genre  Music  Producer
0     False     False     False     False     False  False  False     False
1     False     False     False     False     False  False  False     False
2     False     False     False     False     False  False  False     False
3     False     False     False     False     False  False  False      True
4     False     False     False     False     False  False  False     False
...     ...       ...       ...       ...       ...    ...    ...       ...
3978  False     False     False     False     False  False  False     False
3979  False     False     False     False     False   True  False     False
3980  False     False     False     False     False   True  False     False
3981  False     False     False      True     False  False  False     False
3982  False     False     False     False     False   True  False     False

[3983 rows x 8 columns]

In [52]:
data.loc[3978,'Genre']

'Comedy'

In [53]:
data.loc[3979,'Genre']

nan

In [54]:
data[data['Actors 2'].isnull()]

,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer
161,Videsh,Preity Zinta,NaN,NaN,Deepa Mehta,Drama,Mychael Danna,"Ravi Chopra,David Hamilton"
170,Chhota Bheem And The Curse Of Damyaan,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Rajiv Chilaka,Animation,Sunil Kashyap,Rajiv Chilaka
195,Roadside Romeo,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Jugal Hansraj,Animation,Salim - Sulaiman,"Yash Chopra,Aditya Chopra"
646,Chhota Bheem And The Throne Of Bali,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Rajiv Chilaka,Animation,Sunil Kaushik,Rajiv Chilaka
761,Ashoka The Hero,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Gaurav Jain,Animation,Justin - Uday,Gyanendra Jain
...,...,...,...,...,...,...,...,...
3960,Lovers Point,Sachin Goswami,NaN,NaN,D. Mmgeze,Thriller,NaN,Sachin Goswami
3963,Pihu,Myra Vishwakarma,NaN,NaN,Vinod Kapri,Drama,NaN,"Ronnie Screwvala,Siddharth Roy Kapur,Shilpa Ji..."
3966,Vidyoday,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Vidhi Kasliwal,Documentary,NaN,Vidhi Kasliwal
3969,Bhayanak Aatma of Maria,Sanjay Verma,NaN,NaN,Sanjay Verma,NaN,Vinay Kapoor,Sanjay Verma
3973,Yeh Raat Phir Na Aayegi,Jeetendra,NaN,NaN,Nusrat Sayed,Mystery,Rajesh Roshan,"Shabbir Hussain,Zakir Hussain"

In [55]:
data[data['Director'].isnull()]

,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer
205,Khwaja Mere Khwaja,Raza Murad,Sudhir Dalvi,_x000D__x000D_\n,NaN,Devotional,"Nikhil Kamath,Dilip Tahir",Aalima Ahmed
223,Aap Kaa Surroor,Himesh Reshammiya,Hansika Motwani,Mallika Sherawat,NaN,Drama,Himesh Reshammiya,Vijay Taneja
240,Dus Kahaniyaan,Naseeruddin Shah,Shabana Azmi,Nana Patekar,NaN,Drama,"Bappi Lahiri,Shafqat Ali Khan,Gourov Dasgupta,...","Sanjay Gupta,Sanjay Dutt"
285,Darna Zaroori Hai,Arjun Rampal,Riteish Deshmukh,Mallika Sherawat,NaN,Horror,"Taabhish Romani,Nitin Raikwar,Salim - Sulaiman",Ram Gopal Verma
873,Raat Gayi Baat Gayi,Rajat Kapoor,Iravati Harshe,Dalip Tahil,NaN,Drama,Ankur Tewari,"Rangita Pritish Nandy,Rajat Kapoor,Pritish Nandy"
876,Bombay Talkies,Randeep Hooda,Saqib Saleem,Shivkumar Subramaniam,NaN,Drama,Amit Trivedi,Ashi Dua
892,Shree,NaN,NaN,NaN,NaN,Thriller,NaN,NaN
980,Woh Bewafa Thi,NaN,NaN,NaN,NaN,Love Story,NaN,NaN
1033,Dhama Chaukdi,NaN,NaN,NaN,NaN,Comedy,NaN,NaN
1102,Arjun: The Warrior Prince,NaN,NaN,NaN,NaN,Animation,NaN,NaN
1219,Pyaar Mein Aisa Hota Hai,Aanamika Bawa,NaN,NaN,NaN,Thriller,Shabab Azmi,"Rajesh Kumar,Afsar Khan"
1220,Greater Elephant,NaN,NaN,NaN,NaN,Drama,NaN,NaN
1236,Jayantabhai Ki Love Story,Vivek Oberoi,Neha Sharma,NaN,NaN,Rom - Com,NaN,NaN
1249,Ehsaas,NaN,NaN,NaN,NaN,Drama,NaN,NaN
1364,Jai Maa Maihar Wali,NaN,NaN,NaN,NaN,Drama,NaN,NaN
1365,Tera Junoon,NaN,NaN,NaN,NaN,Love Story,NaN,NaN
1482,Hi Fi Log,Abhay Bakshi,NaN,NaN,NaN,Adult,Baba Jagirdar,NaN
1548,Beda Paar Karte Bhagwan Amarnath,NaN,NaN,NaN,NaN,Devotional,NaN,NaN
1738,Madhu Ki Baatein,NaN,NaN,NaN,NaN,Adult,NaN,NaN
1862,Pyaasa Haiwan,NaN,NaN,NaN,NaN,Horror,NaN,NaN
1869,Pyasi Chandni,NaN,NaN,NaN,NaN,Adult,NaN,NaN
1871,Tu Ladki Hai Badnam Gali Ki,NaN,NaN,NaN,NaN,Drama,NaN,NaN
1875,Aaja Meri Bahon Mein,NaN,NaN,NaN,NaN,Love Story,NaN,NaN
1919,Main Zulm Ko Mitaa Doingi,NaN,NaN,NaN,NaN,Drama,NaN,NaN
1940,Bombay Crime,NaN,NaN,NaN,NaN,Action,NaN,NaN
1953,Saat Saheliyan,NaN,NaN,NaN,NaN,Comedy,NaN,NaN
1979,Memsaab No 1,NaN,NaN,NaN,NaN,Drama,NaN,NaN
2003,Kahaani Saali Jeeja Ki,Amita Nangia,NaN,NaN,NaN,Comedy,Babloo Ustad,Chandini Gupta
2029,Gumnaam Qatil,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2053,Uljhan,Puru Raajkumar,Dipti Bhatnagar,Kanchan,NaN,Drama,Aadesh Shrivastava,Pahlaj Nihalani
2181,Mere Aagosh Mein,NaN,NaN,NaN,NaN,Drama,NaN,NaN
2281,Shuruaat Ka Interval,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,NaN,Documentary,NaN,"Raghavan Bharadwaj,Vinay Mishra,Preety Ali,Pal..."
2375,Arjun Pandit,Sunny Deol,Juhi Chawla,NaN,NaN,Action,NaN,NaN
2376,Tu Hi Meri Ganga,NaN,NaN,NaN,NaN,Love Story,NaN,NaN
2381,Hote Hote Pyaar Ho Gaya,Jackie Shroff,Kajol,NaN,NaN,Love Story,NaN,NaN
2642,Pret Aatma,NaN,NaN,NaN,NaN,Horror,NaN,NaN
2655,Monsoon,Srishti Sharma,Sudhanshu Aggarwal,Shawar Ali,NaN,Drama,Biswajait Bhattacharjee,"Mahendra Dhariwal,Jatinder Gulati"
2855,Paisa Ho Paisa,NaN,NaN,NaN,NaN,Comedy,NaN,NaN
2859,Chaar Cutting,Priyanshu Painyuli,Sonal Joshi,Uday Chandra,NaN,Drama,"Prassanna Vishwanathan,Anjo John,Bonnie Chakra...","Zippy Kimundu,Varun Ralliaram,Ranjan Singh,Noe..."
2862,Chor Bazaari - Ek Atrangi Prem Kahani,NaN,NaN,NaN,NaN,Rom - Com,NaN,NaN
2885,Shaan-E-Elaahi,NaN,NaN,NaN,NaN,Devotional,NaN,NaN
3055,Jai Maa Karwa Chauth,NaN,NaN,NaN,NaN,Devotional,NaN,NaN
3313,Ek Haquiqat Ranjish,NaN,NaN,NaN,NaN,Drama,NaN,NaN
3314,Old Ghost House,NaN,NaN,NaN,NaN,Adult,NaN,NaN
3418,Shor Se Shuruaat,Atul Kulkarni,NaN,NaN,NaN,Drama,NaN,"Pallavi Rohatgi,Preety Ali,Vinay Mishra"
3563,Muskurahatein,J.S. Randhawa,NaN,NaN,NaN,Comedy,Rajat Nagpal,J.S. Randhawa
3706,Raja Abraodiya,NaN,NaN,NaN,NaN,Comedy,NaN,NaN
3747,Falooda,NaN,NaN,NaN,NaN,Comedy,NaN,NaN
3765,For Here Or To Go?,Ali Fazal,Melanie Kannokada,Omi Vadiya,NaN,Drama,"Manesh Judge,Ajit Singh","Vineet Jain,Rucha Humnabadkar,Rishi Bhilawadik..."
3767,Dhadak,Ishaan Khattar,Jahnvi Kapoor,Ashutosh Rana,NaN,Love Story,Ajay - Atul,"Karan Johar,Hiroo Johar,Apoorva Mehta"
3769,Soorma,Diljit Dosanjh,Tapsee Pannu,NaN,NaN,Drama,NaN,NaN
3957,Ilaaka Kishorganj,NaN,NaN,NaN,NaN,Drama,NaN,NaN

In [56]:
data.iloc[170,1]

'_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n'

In [57]:
data['Genre'].value_counts()

Genre
Drama               1529
Action               522
Comedy               466
Love Story           381
Thriller             318
Horror               178
Adult                162
Rom - Com            133
Mystery               97
Masala                53
Devotional            38
Animation             36
Sci Fi / Fantasy      22
Documentary            9
Name: count, dtype: int64

In [58]:
data[data['Genre']=='Animation']

,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer
170,Chhota Bheem And The Curse Of Damyaan,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Rajiv Chilaka,Animation,Sunil Kashyap,Rajiv Chilaka
195,Roadside Romeo,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Jugal Hansraj,Animation,Salim - Sulaiman,"Yash Chopra,Aditya Chopra"
646,Chhota Bheem And The Throne Of Bali,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Rajiv Chilaka,Animation,Sunil Kaushik,Rajiv Chilaka
761,Ashoka The Hero,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Gaurav Jain,Animation,Justin - Uday,Gyanendra Jain
804,The Green Chic,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Sudhir Mehta,Animation,"Jayesh Gandhi,Rajesh Roy,Anaamik,Laxmi - Vasant",NaN
883,Pangaa Gang,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Pankaj Sharma,Animation,Shamir Tandon,"Smita Maroo,Pankaj Sharma"
905,My Friend Ganesha 3,Rahul Pendkalkar,Baba Sehgal,Eva Grover,Rajiv S. Ruia,Animation,"Baba Sehgal,Amjad - Nadeem",Ajhia Acharya
917,Bird Idol,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Jyotin Goel,Animation,"Sangeet - Siddharth,Sangeet - Siddharth",NaN
946,Lava - Kusa,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Dhavala Satyam,Animation,L. Vaidyanathan,Rayudu V. Shashank
972,Ramayana The Epic,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Chetan Desai,Animation,Shaarang Dev,Deepa Sahi
1102,Arjun: The Warrior Prince,NaN,NaN,NaN,NaN,Animation,NaN,NaN
1114,Bal Ganesh 2,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Pankaj Sharma,Animation,"Shamir Tandon,Sanjay Dhakan","Pankaj Sharma,Smita Maroo"
1149,Delhi Safari,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Nikhil Advani,Animation,NaN,"Mukesh Talreja,Kishore Patil"
1153,Krishna Aur Kans,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Vikram Veturi,Animation,Shantanu Moitra,NaN
1162,Sons Of Ram,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Kushal Ruia,Animation,"Shailesh Rao,Gaurav Issar","Kushal Ruia,Jonathan Doton"
1177,Keymon & Nani In Space Adventure,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Nikhal Vyas,Animation,Sandesh Shandilya,NaN
1198,Gunja The Wonder Girl,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Reshma Jaiswal,Animation,Abu Zar,"Reshma Jaiswal,Diwan Singh"
1214,Main Hoon Krishna,Juhi Chawla,Namit Shah,Paresh Ganatra,Rajiv S. Ruia,Animation,Amjad - Nadeem,"Nanda K. Mahto,Promila Hunter"
1321,Ghatothkoch - Master Of Magic,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Singeetam Srinivasa Rao,Animation,Singeetam Srinivasa Rao,"Smita Maroo,Vinod Suryadevara"
1325,Dashavatar,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Bhavik Thakore,Animation,Anand Kurhekar,Vimal Shah
1330,Icy N Spicy,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Anil Goyal,Animation,Dilip Sen,Anil Goyal
1351,Cheenti Cheenti Bang Bang,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,R.D. Mallik,Animation,Jeet Ganguly,"Anirvan Ghose,N.D. Nagpal,R.D. Mallik,Rajiv Ba..."
1362,Jumbo,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Kompin Kemgumnird,Animation,Ram Sampath,NaN
1407,Chhatrapati Shivaji,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,"Azhar Khan,Anand Singh",Animation,"Anandu,Kartikeya Tiwari",Azhar Khan
1500,Bal Ganesh,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Pankaj Sharma,Animation,"Shamir Tandon,Sanjay Dhakan","Pankaj Sharma,Smita Maroo"
1504,Return Of Hanuman,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Anurag Kashyap,Animation,Tapas Relia,NaN
1512,Krishna,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Aman Khan,Animation,"Bappi - Tutal,Rajendra Shiv",Shashikant Chheda
1637,Hanuman,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,V.G. Samant,Animation,Tapas Relia,NaN
1995,Mahabharat,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Aman Khan,Animation,Rajendra Shiv,"Kushal Gada,Dhaval Gada"
2236,Mighty Raju - Rio Calling,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,"Rajiv Chilaka,Anirban Majumder",Animation,Sunil Kaushik,"Rajiv Chilaka,Samir Jain,"
2367,Chaar Sahibzaade,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Harry Baweja,Animation,"Anand Raj Anand,Harry Baweja,Jaidev Kumar",Pammi Baweja
3186,Chhota Bheem Himalayan Adventure,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,"Rajiv Chilaka,Rusauro B Adorable",Animation,John Stewart,"Rajiv Chilaka,Samir Jain"
3387,Motu Patlu King Of Kings,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Suhas Kadav,Animation,"Sandesh Shandilya,Raju Singh,Vishal Bhardwaj","Anish Mehta,Deepa Sahi,Ketan Mehta"
3401,Mahayoddha Rama,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Rohit Vaid,Animation,Aadesh Shrivastava,Abhimanyu Singh
3520,Hanuman Da Damdaar,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Ruchi Narain,Animation,Sneha Khanwalkar,"Ruchi Narain,Taher Shabbir,Ashutosh Shah"
3762,Hanuman Vs Mahiravana,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,Ezhil Vendan,Animation,NaN,"Rajiv Chilaka,Samir Jain,Srinivas Chilakalapudi"

In [59]:
data.drop(data[data['Genre'] == 'Animation'].index, inplace=True)

In [60]:
data.shape

(3947, 8)

In [61]:
data['Genre'].isnull().value_counts()

Genre
False    3908
True       39
Name: count, dtype: int64

In [62]:
data['Director'].isnull().value_counts()

Director
False    3896
True       51
Name: count, dtype: int64

In [63]:
data['Actors 1'].isnull().value_counts()

Actors 1
False    3916
True       31
Name: count, dtype: int64

In [64]:
data[['Actors 2','Actors 3']].isnull().value_counts()

Actors 2  Actors 3
False     False       3074
True      True         647
False     True         159
True      False         67
Name: count, dtype: int64

In [65]:
data[data['Director'].isnull()]

,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer
205,Khwaja Mere Khwaja,Raza Murad,Sudhir Dalvi,_x000D__x000D_\n,NaN,Devotional,"Nikhil Kamath,Dilip Tahir",Aalima Ahmed
223,Aap Kaa Surroor,Himesh Reshammiya,Hansika Motwani,Mallika Sherawat,NaN,Drama,Himesh Reshammiya,Vijay Taneja
240,Dus Kahaniyaan,Naseeruddin Shah,Shabana Azmi,Nana Patekar,NaN,Drama,"Bappi Lahiri,Shafqat Ali Khan,Gourov Dasgupta,...","Sanjay Gupta,Sanjay Dutt"
285,Darna Zaroori Hai,Arjun Rampal,Riteish Deshmukh,Mallika Sherawat,NaN,Horror,"Taabhish Romani,Nitin Raikwar,Salim - Sulaiman",Ram Gopal Verma
873,Raat Gayi Baat Gayi,Rajat Kapoor,Iravati Harshe,Dalip Tahil,NaN,Drama,Ankur Tewari,"Rangita Pritish Nandy,Rajat Kapoor,Pritish Nandy"
876,Bombay Talkies,Randeep Hooda,Saqib Saleem,Shivkumar Subramaniam,NaN,Drama,Amit Trivedi,Ashi Dua
892,Shree,NaN,NaN,NaN,NaN,Thriller,NaN,NaN
980,Woh Bewafa Thi,NaN,NaN,NaN,NaN,Love Story,NaN,NaN
1033,Dhama Chaukdi,NaN,NaN,NaN,NaN,Comedy,NaN,NaN
1219,Pyaar Mein Aisa Hota Hai,Aanamika Bawa,NaN,NaN,NaN,Thriller,Shabab Azmi,"Rajesh Kumar,Afsar Khan"
1220,Greater Elephant,NaN,NaN,NaN,NaN,Drama,NaN,NaN
1236,Jayantabhai Ki Love Story,Vivek Oberoi,Neha Sharma,NaN,NaN,Rom - Com,NaN,NaN
1249,Ehsaas,NaN,NaN,NaN,NaN,Drama,NaN,NaN
1364,Jai Maa Maihar Wali,NaN,NaN,NaN,NaN,Drama,NaN,NaN
1365,Tera Junoon,NaN,NaN,NaN,NaN,Love Story,NaN,NaN
1482,Hi Fi Log,Abhay Bakshi,NaN,NaN,NaN,Adult,Baba Jagirdar,NaN
1548,Beda Paar Karte Bhagwan Amarnath,NaN,NaN,NaN,NaN,Devotional,NaN,NaN
1738,Madhu Ki Baatein,NaN,NaN,NaN,NaN,Adult,NaN,NaN
1862,Pyaasa Haiwan,NaN,NaN,NaN,NaN,Horror,NaN,NaN
1869,Pyasi Chandni,NaN,NaN,NaN,NaN,Adult,NaN,NaN
1871,Tu Ladki Hai Badnam Gali Ki,NaN,NaN,NaN,NaN,Drama,NaN,NaN
1875,Aaja Meri Bahon Mein,NaN,NaN,NaN,NaN,Love Story,NaN,NaN
1919,Main Zulm Ko Mitaa Doingi,NaN,NaN,NaN,NaN,Drama,NaN,NaN
1940,Bombay Crime,NaN,NaN,NaN,NaN,Action,NaN,NaN
1953,Saat Saheliyan,NaN,NaN,NaN,NaN,Comedy,NaN,NaN
1979,Memsaab No 1,NaN,NaN,NaN,NaN,Drama,NaN,NaN
2003,Kahaani Saali Jeeja Ki,Amita Nangia,NaN,NaN,NaN,Comedy,Babloo Ustad,Chandini Gupta
2029,Gumnaam Qatil,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2053,Uljhan,Puru Raajkumar,Dipti Bhatnagar,Kanchan,NaN,Drama,Aadesh Shrivastava,Pahlaj Nihalani
2181,Mere Aagosh Mein,NaN,NaN,NaN,NaN,Drama,NaN,NaN
2281,Shuruaat Ka Interval,_x000D__x000D_\n_x000D__x000D_\n_x000D__x000D_\n,NaN,NaN,NaN,Documentary,NaN,"Raghavan Bharadwaj,Vinay Mishra,Preety Ali,Pal..."
2375,Arjun Pandit,Sunny Deol,Juhi Chawla,NaN,NaN,Action,NaN,NaN
2376,Tu Hi Meri Ganga,NaN,NaN,NaN,NaN,Love Story,NaN,NaN
2381,Hote Hote Pyaar Ho Gaya,Jackie Shroff,Kajol,NaN,NaN,Love Story,NaN,NaN
2642,Pret Aatma,NaN,NaN,NaN,NaN,Horror,NaN,NaN
2655,Monsoon,Srishti Sharma,Sudhanshu Aggarwal,Shawar Ali,NaN,Drama,Biswajait Bhattacharjee,"Mahendra Dhariwal,Jatinder Gulati"
2855,Paisa Ho Paisa,NaN,NaN,NaN,NaN,Comedy,NaN,NaN
2859,Chaar Cutting,Priyanshu Painyuli,Sonal Joshi,Uday Chandra,NaN,Drama,"Prassanna Vishwanathan,Anjo John,Bonnie Chakra...","Zippy Kimundu,Varun Ralliaram,Ranjan Singh,Noe..."
2862,Chor Bazaari - Ek Atrangi Prem Kahani,NaN,NaN,NaN,NaN,Rom - Com,NaN,NaN
2885,Shaan-E-Elaahi,NaN,NaN,NaN,NaN,Devotional,NaN,NaN
3055,Jai Maa Karwa Chauth,NaN,NaN,NaN,NaN,Devotional,NaN,NaN
3313,Ek Haquiqat Ranjish,NaN,NaN,NaN,NaN,Drama,NaN,NaN
3314,Old Ghost House,NaN,NaN,NaN,NaN,Adult,NaN,NaN
3418,Shor Se Shuruaat,Atul Kulkarni,NaN,NaN,NaN,Drama,NaN,"Pallavi Rohatgi,Preety Ali,Vinay Mishra"
3563,Muskurahatein,J.S. Randhawa,NaN,NaN,NaN,Comedy,Rajat Nagpal,J.S. Randhawa
3706,Raja Abraodiya,NaN,NaN,NaN,NaN,Comedy,NaN,NaN
3747,Falooda,NaN,NaN,NaN,NaN,Comedy,NaN,NaN
3765,For Here Or To Go?,Ali Fazal,Melanie Kannokada,Omi Vadiya,NaN,Drama,"Manesh Judge,Ajit Singh","Vineet Jain,Rucha Humnabadkar,Rishi Bhilawadik..."
3767,Dhadak,Ishaan Khattar,Jahnvi Kapoor,Ashutosh Rana,NaN,Love Story,Ajay - Atul,"Karan Johar,Hiroo Johar,Apoorva Mehta"
3769,Soorma,Diljit Dosanjh,Tapsee Pannu,NaN,NaN,Drama,NaN,NaN
3957,Ilaaka Kishorganj,NaN,NaN,NaN,NaN,Drama,NaN,NaN

In [66]:
data.head()

,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer
0,Agneepath,Rishi Kapoor,Sanjay Dutt,Hrithik Roshan,Karan Malhotra,Action,Ajay - Atul,"Karan Johar,Hiroo Johar"
1,Bittoo Boss,Pulkit Samrat,Amita Pathak,Rajesh Bakshi,Supavitra Babul,Love Story,Raghav Sachar,"Abhishek Pathak,Kumar Mangat"
2,Housefull 2,Akshay Kumar,John Abraham,Rishi Kapoor,Sajid Khan,Comedy,Sajid - Wajid,Sajid Nadiadwala
3,Singham,Ajay Devgn,Kajal Aggarwal,Prakash Raj,Rohit Shetty,Action,Ajay - Atul,NaN
4,Golmaal 3,Mithun Chakraborty,Ajay Devgn,Kareena Kapoor,Rohit Shetty,Comedy,Pritam,Dillion Mehta

In [67]:
datas=data.fillna('Unknown')

In [68]:
data.shape

(3947, 8)

In [69]:
datas.shape

(3947, 8)

In [70]:
data['Director'].isnull().value_counts()

Director
False    3896
True       51
Name: count, dtype: int64

In [71]:
data['Actors 1'].isnull().value_counts()

Actors 1
False    3916
True       31
Name: count, dtype: int64

In [72]:
data.isnull()

      Title  Actors 1  Actors 2  Actors 3  Director  Genre  Music  Producer
0     False     False     False     False     False  False  False     False
1     False     False     False     False     False  False  False     False
2     False     False     False     False     False  False  False     False
3     False     False     False     False     False  False  False      True
4     False     False     False     False     False  False  False     False
...     ...       ...       ...       ...       ...    ...    ...       ...
3978  False     False     False     False     False  False  False     False
3979  False     False     False     False     False   True  False     False
3980  False     False     False     False     False   True  False     False
3981  False     False     False      True     False  False  False     False
3982  False     False     False     False     False   True  False     False

[3947 rows x 8 columns]

In [73]:
data[data.isnull()=='True']

     Title Actors 1 Actors 2 Actors 3 Director Genre Music Producer
0      NaN      NaN      NaN      NaN      NaN   NaN   NaN      NaN
1      NaN      NaN      NaN      NaN      NaN   NaN   NaN      NaN
2      NaN      NaN      NaN      NaN      NaN   NaN   NaN      NaN
3      NaN      NaN      NaN      NaN      NaN   NaN   NaN      NaN
4      NaN      NaN      NaN      NaN      NaN   NaN   NaN      NaN
...    ...      ...      ...      ...      ...   ...   ...      ...
3978   NaN      NaN      NaN      NaN      NaN   NaN   NaN      NaN
3979   NaN      NaN      NaN      NaN      NaN   NaN   NaN      NaN
3980   NaN      NaN      NaN      NaN      NaN   NaN   NaN      NaN
3981   NaN      NaN      NaN      NaN      NaN   NaN   NaN      NaN
3982   NaN      NaN      NaN      NaN      NaN   NaN   NaN      NaN

[3947 rows x 8 columns]

In [74]:
data.head()

,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer
0,Agneepath,Rishi Kapoor,Sanjay Dutt,Hrithik Roshan,Karan Malhotra,Action,Ajay - Atul,"Karan Johar,Hiroo Johar"
1,Bittoo Boss,Pulkit Samrat,Amita Pathak,Rajesh Bakshi,Supavitra Babul,Love Story,Raghav Sachar,"Abhishek Pathak,Kumar Mangat"
2,Housefull 2,Akshay Kumar,John Abraham,Rishi Kapoor,Sajid Khan,Comedy,Sajid - Wajid,Sajid Nadiadwala
3,Singham,Ajay Devgn,Kajal Aggarwal,Prakash Raj,Rohit Shetty,Action,Ajay - Atul,NaN
4,Golmaal 3,Mithun Chakraborty,Ajay Devgn,Kareena Kapoor,Rohit Shetty,Comedy,Pritam,Dillion Mehta

In [75]:
data['Genre'].value_counts()

Genre
Drama               1529
Action               522
Comedy               466
Love Story           381
Thriller             318
Horror               178
Adult                162
Rom - Com            133
Mystery               97
Masala                53
Devotional            38
Sci Fi / Fantasy      22
Documentary            9
Name: count, dtype: int64

In [76]:
datas['Genre'].value_counts()

Genre
Drama               1529
Action               522
Comedy               466
Love Story           381
Thriller             318
Horror               178
Adult                162
Rom - Com            133
Mystery               97
Masala                53
Unknown               39
Devotional            38
Sci Fi / Fantasy      22
Documentary            9
Name: count, dtype: int64

In [77]:
data.shape

(3947, 8)

In [78]:
data.isnull()

      Title  Actors 1  Actors 2  Actors 3  Director  Genre  Music  Producer
0     False     False     False     False     False  False  False     False
1     False     False     False     False     False  False  False     False
2     False     False     False     False     False  False  False     False
3     False     False     False     False     False  False  False      True
4     False     False     False     False     False  False  False     False
...     ...       ...       ...       ...       ...    ...    ...       ...
3978  False     False     False     False     False  False  False     False
3979  False     False     False     False     False   True  False     False
3980  False     False     False     False     False   True  False     False
3981  False     False     False      True     False  False  False     False
3982  False     False     False     False     False   True  False     False

[3947 rows x 8 columns]

In [79]:
 data.tail()

,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer
3978,P.K. Lele - A Salesman,Manav Sohal,Brijendra Kala,Shravani Goswami,Manav Sohal,Comedy,Nayab,"Manav Sohal,Shailesh Gosrani"
3979,Dhappa,Shresth Kumar,Varsha Manikchand,Ayub Khan,Siddharth Nagar,NaN,Vivek Bakshi,Siddharth Nagar
3980,Bhaagte Raho,Abhay Kabir Raichand,Riya Deepsi,Rajpal Yadav,Praful Tiwari,NaN,Hyperbol,Sunil Tiwari
3981,Mumbhaii Gangster,Sanjay Kapoor,Mahima Chaudhary,NaN,Rajiv Ranjan Das,Drama,Liyaqat Ajmeri,Sanjay Shah
3982,Simmba,Ranveer Singh,Sara Ali Khan,Ashutosh Rana,Rohit Shetty,NaN,"DJ Chetas,Lijo George,Tanishk","Rohit Shetty,Karan Johar,Hiroo Johar,Apoorva M..."

In [80]:
data.isnull().sum()

Title         0
Actors 1     31
Actors 2    714
Actors 3    806
Director     51
Genre        39
Music       177
Producer    354
dtype: int64

In [81]:
data['Genre'].value_counts()

Genre
Drama               1529
Action               522
Comedy               466
Love Story           381
Thriller             318
Horror               178
Adult                162
Rom - Com            133
Mystery               97
Masala                53
Devotional            38
Sci Fi / Fantasy      22
Documentary            9
Name: count, dtype: int64

In [82]:
data[data['Title']=='Dangal']

,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer
3421,Dangal,Aamir Khan,Sakshi Tanwar,Fatima Sana Shaikh,Nitish Tiwari,Drama,Pritam,"Aamir Khan,Kiran Rao,Siddharth Roy Kapur"

In [83]:
datas=data.dropna(subset=['Genre', 'Director', 'Actors 1','Actors 2', 'Actors 3','Producer','Music'], inplace=True)

In [84]:
data.shape

(2767, 8)

In [85]:
data[data.isnull()=='True']

     Title Actors 1 Actors 2 Actors 3 Director Genre Music Producer
0      NaN      NaN      NaN      NaN      NaN   NaN   NaN      NaN
1      NaN      NaN      NaN      NaN      NaN   NaN   NaN      NaN
2      NaN      NaN      NaN      NaN      NaN   NaN   NaN      NaN
4      NaN      NaN      NaN      NaN      NaN   NaN   NaN      NaN
5      NaN      NaN      NaN      NaN      NaN   NaN   NaN      NaN
...    ...      ...      ...      ...      ...   ...   ...      ...
3970   NaN      NaN      NaN      NaN      NaN   NaN   NaN      NaN
3971   NaN      NaN      NaN      NaN      NaN   NaN   NaN      NaN
3974   NaN      NaN      NaN      NaN      NaN   NaN   NaN      NaN
3975   NaN      NaN      NaN      NaN      NaN   NaN   NaN      NaN
3978   NaN      NaN      NaN      NaN      NaN   NaN   NaN      NaN

[2767 rows x 8 columns]

In [86]:
data.isnull().sum()

Title       0
Actors 1    0
Actors 2    0
Actors 3    0
Director    0
Genre       0
Music       0
Producer    0
dtype: int64

In [87]:
data['Genre'].isnull().sum()

np.int64(0)

# Reccomendation System

In [88]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [89]:
vectorizor=TfidfVectorizer()

In [90]:
Model=vectorizor.fit_transform(data[['Title','Actors 1', 'Actors 2','Actors 3', 'Director','Genre', 'Music','Producer']])

In [91]:
type(Model)

scipy.sparse._csr.csr_matrix

In [92]:
from sklearn.metrics.pairwise import cosine_similarity

In [93]:
similarity=cosine_similarity(Model)

In [94]:

selected_cols = ['Title', 'Actors 1', 'Actors 2', 'Actors 3', 'Director', 'Genre', 'Music', 'Producer']


data[selected_cols] = data[selected_cols].fillna('')


data['combined'] = data[selected_cols].astype(str).agg(' '.join, axis=1)


vectorizer = TfidfVectorizer()
Model = vectorizer.fit_transform(data['combined'])


similarity = cosine_similarity(Model)

def recommend(movie_title):
    movie_title = movie_title.lower()
    
    # Title case sensitive 
    index = data[data['Actors 1'].str.lower() == movie_title].index.tolist()
    
    if len(index) == 0:
        return "Movie not found in dataset."

    index = index[0]

    # Similarity scores
    scores = list(enumerate(similarity[index]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)

    # Top 5 similar movies
    top_movies = scores[1:6]

    print(f"\nTop 5 recommendations for '{data.iloc[index]['Title']}':\n")
    for i, score in top_movies:
        print(f"{data.iloc[i]['Title']} (Score: {round(score, 2)})")

recommend("Akshay Kumar")

Top 5 recommendations for 'Housefull 2':

Housefull (Score: 0.61)
Housefull 3 (Score: 0.47)
Heyy Babyy (Score: 0.43)
Mujhse Shaadi Karogi (Score: 0.43)
Kick (Score: 0.36)

In [95]:
data.reset_index(drop=True, inplace=True)

In [96]:
import joblib
joblib.dump(vectorizer, 'tfidf_vectorizer.pkl')

['tfidf_vectorizer.pkl']

In [97]:
joblib.dump(similarity, 'similarity.pkl')

['similarity.pkl']

In [98]:
joblib.dump(data, 'movies_data.pkl')

['movies_data.pkl']

In [99]:
data.head()

,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer,combined
0,Agneepath,Rishi Kapoor,Sanjay Dutt,Hrithik Roshan,Karan Malhotra,Action,Ajay - Atul,"Karan Johar,Hiroo Johar",Agneepath Rishi Kapoor Sanjay Dutt Hrithik Ros...
1,Bittoo Boss,Pulkit Samrat,Amita Pathak,Rajesh Bakshi,Supavitra Babul,Love Story,Raghav Sachar,"Abhishek Pathak,Kumar Mangat",Bittoo Boss Pulkit Samrat Amita Pathak Rajesh ...
2,Housefull 2,Akshay Kumar,John Abraham,Rishi Kapoor,Sajid Khan,Comedy,Sajid - Wajid,Sajid Nadiadwala,Housefull 2 Akshay Kumar John Abraham Rishi Ka...
3,Golmaal 3,Mithun Chakraborty,Ajay Devgn,Kareena Kapoor,Rohit Shetty,Comedy,Pritam,Dillion Mehta,Golmaal 3 Mithun Chakraborty Ajay Devgn Kareen...
4,Kahaani,Vidya Balan,Nawazuddin Siddiqui,Parambrata Chatterjee,Sujoy Ghosh,Thriller,Vishal - Shekhar,"Sujoy Ghosh,Kushal Gada",Kahaani Vidya Balan Nawazuddin Siddiqui Paramb...

In [100]:
data.tail()

,Title,Actors 1,Actors 2,Actors 3,Director,Genre,Music,Producer,combined
2762,Bhaiaji Superhittt,Sunny Deol,Preity Zinta,Ameesha Patel,Neeraj Pathak,Masala,"Amjad - Nadeem,Neeraj Pathak,Jeet Ganguly,Ragh...",Chirag Mahendra Dhariwal,Bhaiaji Superhittt Sunny Deol Preity Zinta Ame...
2763,2,Rajnikant,Akshay Kumar,Amy Jackson,S. Shankar,Sci Fi / Fantasy,A.R. Rehman,A. Subaskaran,2 Rajnikant Akshay Kumar Amy Jackson S. Shanka...
2764,Geet,Avinash Wadhavan,Divya Bharti,Laxmikant Berde,Partho Ghosh,Love Story,Bappi Lahiri,Nilima Paul,Geet Avinash Wadhavan Divya Bharti Laxmikant B...
2765,Zero,Shahrukh Khan,Anushka Sharma,Katrina Kaif,Anand L. Rai,Love Story,Ajay - Atul,Gauri Khan,Zero Shahrukh Khan Anushka Sharma Katrina Kaif...
2766,P.K. Lele - A Salesman,Manav Sohal,Brijendra Kala,Shravani Goswami,Manav Sohal,Comedy,Nayab,"Manav Sohal,Shailesh Gosrani",P.K. Lele - A Salesman Manav Sohal Brijendra K...